# Loading JSON Data into Pandas DataFrame

This notebook demonstrates how to load JSON data from a file or API into a pandas DataFrame for data analysis and manipulation.

In [ ]:
import requests
import pandas as pd

url = "https://api.worldaquatics.com/fina/athletes/1001621/results"
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

# Convert to pandas DataFrame
michael_Phelps = pd.DataFrame(data["Results"])

michael_Phelps.head()

,Rank,MedalTag,SportCode,DisciplineName,PhaseName,RecordType,NAT,CompetitionName,CompetitionType,CompetitionCountry,CompetitionCity,Date,Time,UtcDateTime,Points,Tags,AthleteResultAge
0,1.0,G,SW,Men 4x100m Medley Relay,Finals,OR,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-13,3:27.95,2016-08-14T02:04:00,990.0,None,31
1,2.0,S,SW,Men 100m Butterfly,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-12,51.14,2016-08-13T01:12:00,924.0,None,31
2,1.0,G,SW,Men 200m Medley,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-11,1:54.66,2016-08-12T02:01:00,982.0,None,31
3,1.0,G,SW,Men 4x200m Freestyle Relay,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-09,7:00.66,2016-08-10T02:38:00,985.0,None,31
4,1.0,G,SW,Men 200m Butterfly,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-09,1:53.36,2016-08-10T01:28:00,951.0,None,31

In [ ]:
import requests
import pandas as pd

url = "https://api.worldaquatics.com/fina/athletes/1007320/results"
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

# Convert to pandas DataFrame
laszlo_Cseh = pd.DataFrame(data["Results"])

laszlo_Cseh.head()

In [9]:
michael_Phelps = michael_Phelps.drop(columns=["SportCode", "MedalTag", "PhaseName", "CompetitionCity", "UtcDateTime", "Tags", "Points"])
michael_Phelps.head()

,Rank,DisciplineName,RecordType,NAT,CompetitionName,CompetitionType,CompetitionCountry,Date,Time,AthleteResultAge
0,1.0,Men 4x100m Medley Relay,OR,USA,Olympic Games Rio 2016,Olympic Games,BRA,2016-08-13,3:27.95,31
1,2.0,Men 100m Butterfly,,USA,Olympic Games Rio 2016,Olympic Games,BRA,2016-08-12,51.14,31
2,1.0,Men 200m Medley,,USA,Olympic Games Rio 2016,Olympic Games,BRA,2016-08-11,1:54.66,31
3,1.0,Men 4x200m Freestyle Relay,,USA,Olympic Games Rio 2016,Olympic Games,BRA,2016-08-09,7:00.66,31
4,1.0,Men 200m Butterfly,,USA,Olympic Games Rio 2016,Olympic Games,BRA,2016-08-09,1:53.36,31